title : حمزه جوادی شکرو
author: حمزه جوادی شکرو
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://javadi.daloo.ir"
description: "اندیشه هایی خام به قلم حمزه جوادی شکرو."
github: hjavadish
virgool: hjavadish
medium: hjavadish
permalink: none
encoding: utf-8

paginate: 20
paginate_path: /page:num/

markdown: kramdown
tag_page_layout: tag_page
tag_page_dir: tags

collections: 
  projects:
    output: true
  books:
   output: true



plugins:
   - jekyll-jalali
   - jekyll-paginate
   - jekyll/tagging
